AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.2

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

inherit_from: .rubocop_todo.yml
