require:
  - rubocop-performance

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.3

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Code is currently broken with frozen string literal comments applied.
# TODO: Enable and fix build
Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml
