language: ruby
script: bundle exec rake test
before_install:
  - gem install bundler -v '< 2'
bundler_args: --without debug

jobs:
  include:
    - rvm: ruby-head
      stage: test
      os: linux
    - rvm: ruby-head
      os: osx
    - rvm: 2.6.3
      os: linux
    - rvm: 2.6.3
      os: osx
    - rvm: 2.5.5
      os: linux
    - rvm: 2.5.5
      os: osx
    - rvm: 2.4.6
      os: linux
    - rvm: 2.4.6
      os: osx
    - rvm: 2.3.8
      os: linux
    - rvm: 2.3.8
      os: osx
    - rvm: 2.3.0
      os: linux
    - rvm: jruby
      os: linux
    - rvm: jruby-9.2.6.0
      os: linux
    - rvm: jruby-9.2.6.0
      os: osx
      env: JAVA_OPTS="--add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/javax.crypto=ALL-UNNAMED --add-opens java.base/java.security.cert=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --illegal-access=warn"
    - stage: lint
      script: bundle exec rake lint
      rvm: 2.6.3
      os: linux
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master
    - still

# notifications:
#   slack: cucumberbdd:oQFVhzsx4R94KWmjlejAJYnM
env:
  global:
    - secure: l8uznA5K4K9mZ1krmP3lTMD8WcJ32qGxFOR3jubKHcOBSLB4xSzU2aIqjyJdO+rLzebkwamhJc8pGSIWOUDQYvFiX7splK+uEkbBJ5huAhXtLF4Qgl86bCWbEXYzN7rvn0DQfpJAovyFMNRMnfo70XhwqWzFsaYa7Z0YbqYsJE4=
    # Travis by default also have "-Dcext.enabled=false" set in
    # JRUBY_OPTS, but JRuby 9 does not support C extensions at all
    # so it issues warning that will mess up the stderr checks.
    - JRUBY_OPTS="--dev --debug"
    # Somehow a "ASCII-8BIT to UTF-8 conversion error" appears for
    # JRuby 9
    - LC_ALL=en_US.UTF-8
    - LANG=en_US.UTF-8
    - LANGUAGE=en_US.UTF-8
