sudo: false
language: ruby
script: script/test
install: script/bootstrap --without development debug
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-1.7.26
  - jruby-20mode
  - jruby-21mode
  - rbx
matrix:
  include:
    - rvm: jruby-9.0.1.0
    - rvm: jruby-9.0.1.0-20mode
    - rvm: jruby-9.0.1.0-21mode
  allow_failures:
  - rvm: rbx
  - rvm: jruby-9.0.1.0
  - rvm: jruby-9.0.1.0-20mode
  - rvm: jruby-9.0.1.0-21mode
branches:
  only:
    - master
    - still
env:
  - JRUBY_OPTS='--dev'
